ALTER TABLE "trabajos_impresion" ADD COLUMN     "coaVistas" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "coaDescargas" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fdsVistas" INTEGER NOT NULL DEFAULT 0;
